name: play_games
description: A simple wrapper on top of Google Play Games Services (GPGS), including auth, achievement, and more.
version: 0.5.4
homepage: https://github.com/luanpotter/play_games

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.games.play.playgames
        pluginClass: PlayGamesPlugin
      ios:
        pluginClass: AudioplayersPlugin
